server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      force: true
  error:
    include-binding-errors: never
    include-exception: false
    include-message: never
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "0000"
#    url: jdbc:h2:mem:test;MODE=MySQL
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: always
logging:
  level:
    shop.woosung.bank: DEBUG
    org.hibernate.type: TRACE